Add Route Structure, required parameters, and url matchings to backend README.md
white-van/discussion-board pull request #23
Opened 2020-12-23 04:06 UTC by SAbbas2018

## [DEV-006] Backend Boilerplate

Fixes: #1 

-   [Y] Has the code been formatted? (N/A)
-   [Y] Have dependencies/packages been added? (N/A)

### Changes
Added to Route structure, URL matching, and possible parameters required in the queries.

### Testing
-   [Y] Does the code have sufficient automated test coverage? If not, include a reasoning and steps required to manually QA (N/A)

2020-12-23 17:11 UTC, jcserv requested changes
Nice work, just a few minor fixes.
Can you also update the README.md in the root directory for the backend project structure?

2020-12-23 17:11 UTC, jcserv commented on backend/README.md
>  # Pizza Backend
We're going by Dialog!

2020-12-23 17:11 UTC, jcserv commented on backend/README.md
> +    user_router.POST("/register", handleUserRegister) // The request respondst to the url matching "/user/register" and should include
move this to the next line, it's a bit difficult to read. same for the other routes!

2020-12-23 17:11 UTC, jcserv commented on backend/README.md
> +    Should we add a reset password for a user route when we add authentication ?
definitely, good thinking

2020-12-23 17:11 UTC, jcserv commented on backend/README.md
> +specific_user_router := router.Group("/user/:user_id"){
can we do uid?
not as readable but it looks nicer 😎 

similarly, cid for course_id & tid for thread_id

Q: @krishchow 
is golang pothole case or camel case?
the naming for the id variables follows pothole case but in other instances of this file we use camelcase.

2020-12-23 17:11 UTC, jcserv commented on backend/README.md
> +    specific_user_router.PUT("/:course_id/:thread_id/:comment_id/upVote", handleUpVote) // The request responds to the url matching "/users/:user_id/:course_id/:thread_id/:comment_id/upVote"
i think the v in upvote doesn't need to be capitallized

2020-12-23 17:11 UTC, jcserv commented on backend/README.md
> +    // PUT can be replaced by PATCH, since both can be used for Updating, but PATCH seems to be for modfiying, maybe use PATCH here instead?
some typos here:

Updating -> updating
modfiying -> modifying

in regards to the question: i agree that PATCH would be better than PUT based on the definition here:
```
PUT method uses the request URI to supply a modified version of the requested resource which replaces the original version of the resource, whereas the PATCH method supplies a set of instructions to modify the resource.
```

2020-12-23 17:59 UTC, SAbbas2018 commented
Fixed all the issues above. I have converted everything to **camelCase**, added the backend structure to the root README.md and added terminology in the backend/README.md.

2020-12-23 22:45 UTC, jcserv approved these changes
Great work on the fixes, I like the shorthand legend

2020-12-24 03:03 UTC, AipioxTechson approved these changes

2020-12-24 03:19 UTC, merged